import pptxgen from "pptxgenjs";
import { DocumentSpec, DesignStyle } from "@/types/document-spec";
import { PPTX_DIMENSIONS } from "@/lib/layout-engine/grid-calculator";
import { resolvePptxDesignTokens } from "./design-tokens";
import { visualDirectionTracer } from "@/lib/ai/visual-direction-tracer";
import {
  RenderContext,
  renderTitleSlide,
  renderTitleAndContent,
  renderTwoColumn,
  renderThreeColumn,
  renderFullBleedVisual,
  renderBigStatistic,
  renderComparison,
  renderTimeline,
  renderProcessFlow,
  renderDiagram,
  renderChart,
  renderTable,
  renderQuote,
  renderSectionDivider,
  renderSummary,
  renderClosingSlide,
} from "./layout-renderers";

export interface PptxCompileOptions {
  designStyle?: DesignStyle | string;
  enableQualityProtection?: boolean;
  projectId?: string;
  documentId?: string;
}

/**
 * Deterministic PPTX Compiler
 * Transforms a validated DocumentSpec AST into a 100% native, fully editable PowerPoint file.
 * Every slide element (text, shape, table, chart, connector, line, header, footer) is generated
 * as a native Office XML object.
 */
export async function compileDocumentToPptx(
  doc: DocumentSpec,
  options: PptxCompileOptions = {}
): Promise<pptxgen> {
  const pptx = new pptxgen();
  const projectId = options.projectId || (doc as any).id || "proj-export";
  const documentId = options.documentId || (doc as any).id || "doc-export";
  const visualDirection = doc.visualDirection;

  if (visualDirection) {
    visualDirectionTracer.recordTrace({
      projectId,
      documentId,
      visualDirectionId: visualDirection.id,
      variationSeed: visualDirection.variationSeed,
      styleFamily: visualDirection.styleFamily,
      stage: "PPTX_COMPILATION_STARTED",
      generatedAtStage: "pptx-builder",
      consumedBy: "PPTX Compiler",
      metadata: { totalSlides: doc.pages.length },
    });
  }

  // 1. Configure presentation dimensions
  const dims = PPTX_DIMENSIONS[doc.canvas.aspectRatio] || PPTX_DIMENSIONS["16:9"];
  pptx.defineLayout({
    name: "CUSTOM_SLIDECRAFT",
    width: dims.wInches,
    height: dims.hInches,
  });
  pptx.layout = "CUSTOM_SLIDECRAFT";

  // 2. Set presentation core metadata
  pptx.title = doc.meta.title || "SlideCraft Presentation";
  pptx.subject = doc.meta.description || "Generated by SlideCraft AI Enterprise Studio";
  pptx.author = doc.meta.author || "SlideCraft AI";
  pptx.company = "SlideCraft AI";

  // 3. Resolve design tokens
  const tokens = resolvePptxDesignTokens(
    doc.theme,
    options.designStyle || doc.meta.designStyle
  );

  const ctx: RenderContext = {
    slideW: dims.wInches,
    slideH: dims.hInches,
    tokens,
    pptx,
    totalSlides: doc.pages.length,
  };

  // 4. Render each slide
  for (const page of doc.pages) {
    const slide = pptx.addSlide();

    // Slide Background Base
    const bgSpec = page.backgroundSpec || (visualDirection ? {
      type: "gradient" as const,
      gradient: visualDirection.gradient,
      pattern: (visualDirection.texturePattern?.type !== "none" ? visualDirection.texturePattern?.type : undefined) as any,
      glow: visualDirection.glow,
      decorativeShapes: visualDirection.decorativeShapes,
    } : undefined);

    const slideBg = bgSpec?.gradient?.stops?.[0]?.color
      ? bgSpec.gradient.stops[0].color.replace(/^#/, "")
      : page.backgroundOverride
      ? page.backgroundOverride.replace(/^#/, "")
      : tokens.colors.background;
    slide.background = { color: slideBg };

    // Dynamic Gradient Simulation (Secondary Translucent Rect Wash)
    if (bgSpec?.gradient?.stops && bgSpec.gradient.stops.length > 1) {
      const stop2Hex = bgSpec.gradient.stops[1].color.replace(/^#/, "");
      try {
        slide.addShape("rect", {
          x: 0,
          y: 0,
          w: dims.wInches,
          h: dims.hInches,
          fill: { color: stop2Hex, transparency: 70 },
          line: { color: stop2Hex, transparency: 100 },
        });
      } catch {
        // ignore shape error
      }
    }

    // Dynamic Ambient Glow in PPTX
    const glow = bgSpec?.glow || visualDirection?.glow;
    if (glow) {
      const glowHex = glow.color.replace(/^#/, "");
      const secHex = ((glow as any).secondaryColor || tokens.colors.accent || tokens.colors.secondary || glow.color).replace(/^#/, "");
      
      const glowScale = glow.scale ?? 1.2;
      const glowW = 4.2 * glowScale;
      const glowH = 3.5 * glowScale;
      let glowX = dims.wInches - 3.8;
      let glowY = dims.hInches - 3.2;

      if (glow.position === "top_left") {
        glowX = -1.0;
        glowY = -1.0;
      } else if (glow.position === "top_right") {
        glowX = dims.wInches - 3.2;
        glowY = -1.0;
      } else if (glow.position === "bottom_left") {
        glowX = -1.0;
        glowY = dims.hInches - 3.0;
      } else if (glow.position === "bottom_right") {
        glowX = dims.wInches - 3.5;
        glowY = dims.hInches - 3.0;
      } else if (glow.position === "center") {
        glowX = (dims.wInches - glowW) / 2;
        glowY = (dims.hInches - glowH) / 2;
      } else if (glow.position === "asymmetric") {
        glowX = dims.wInches - 3.2;
        glowY = -1.0;
      }

      try {
        slide.addShape("ellipse", {
          x: glowX,
          y: glowY,
          w: glowW,
          h: glowH,
          fill: { color: glowHex, transparency: 86 },
          line: { color: glowHex, transparency: 100 },
        });

        if (glow.position === "asymmetric") {
          slide.addShape("ellipse", {
            x: -1.0,
            y: dims.hInches - 2.8,
            w: 3.2,
            h: 3.2,
            fill: { color: secHex, transparency: 90 },
            line: { color: secHex, transparency: 100 },
          });
        }
      } catch {
        // ignore shape error
      }
    }

    // Dynamic Decorative Shapes in PPTX
    const rawShapes = bgSpec?.decorativeShapes || visualDirection?.decorativeShapes;
    const shapeStyle = (rawShapes as any)?.style || (rawShapes as any)?.type;
    const shapePos = ((rawShapes as any)?.position || "top_right") as string;
    if (rawShapes && shapeStyle && shapeStyle !== "none") {
      const shapeColor = rawShapes.color ? rawShapes.color.replace(/^#/, "") : tokens.colors.primary;
      const shapeSecColor = ((rawShapes as any)?.secondaryColor || tokens.colors.accent || shapeColor).replace(/^#/, "");
      
      try {
        if (shapeStyle === "geometric_circles") {
          const cx = shapePos.includes("right") ? dims.wInches - 1.8 : 0.4;
          const cy = shapePos.includes("bottom") ? dims.hInches - 1.8 : 0.4;
          slide.addShape("ellipse", {
            x: cx - 1.2,
            y: cy - 1.2,
            w: 2.4,
            h: 2.4,
            fill: { color: shapeColor, transparency: 100 },
            line: { color: shapeColor, width: 1, transparency: 80, dashType: "dash" },
          });
          slide.addShape("ellipse", {
            x: cx - 0.8,
            y: cy - 0.8,
            w: 1.6,
            h: 1.6,
            fill: { color: shapeSecColor, transparency: 100 },
            line: { color: shapeSecColor, width: 0.75, transparency: 75 },
          });
        } else if (shapeStyle === "accent_rail") {
          slide.addShape("rect", {
            x: dims.wInches - 0.35,
            y: 0.6,
            w: 0.03,
            h: dims.hInches - 1.2,
            fill: { color: shapeColor, transparency: 70 },
            line: { color: shapeColor, transparency: 100 },
          });
        } else if (shapeStyle === "tech_brackets") {
          slide.addShape("rect", {
            x: dims.wInches - 0.8,
            y: 0.4,
            w: 0.4,
            h: 0.02,
            fill: { color: shapeColor, transparency: 65 },
            line: { color: shapeColor, transparency: 100 },
          });
          slide.addShape("rect", {
            x: dims.wInches - 0.42,
            y: 0.4,
            w: 0.02,
            h: 0.4,
            fill: { color: shapeColor, transparency: 65 },
            line: { color: shapeColor, transparency: 100 },
          });
        } else if (shapeStyle === "corner_frame") {
          slide.addShape("rect", {
            x: 0.5,
            y: 0.5,
            w: 0.5,
            h: 0.02,
            fill: { color: shapeColor, transparency: 60 },
            line: { color: shapeColor, transparency: 100 },
          });
          slide.addShape("rect", {
            x: 0.5,
            y: 0.5,
            w: 0.02,
            h: 0.5,
            fill: { color: shapeColor, transparency: 60 },
            line: { color: shapeColor, transparency: 100 },
          });
        } else if (shapeStyle === "editorial_lines") {
          slide.addShape("rect", {
            x: 0.8,
            y: 0.5,
            w: dims.wInches - 1.6,
            h: 0.015,
            fill: { color: shapeColor, transparency: 82 },
            line: { color: shapeColor, transparency: 100 },
          });
        }
      } catch {
        // ignore shape error
      }
    }

    // Speaker Notes
    if (page.notes) {
      slide.addNotes(page.notes);
    }

    // Archetype-Specific Layout Dispatch
    const archetype = page.archetype;
    switch (archetype) {
      case "hero_title":
        renderTitleSlide(slide, page, ctx);
        break;

      case "title_and_content":
        renderTitleAndContent(slide, page, ctx);
        break;

      case "two_column_split":
      case "two_column":
        renderTwoColumn(slide, page, ctx);
        break;

      case "three_card_grid":
      case "three_column":
        renderThreeColumn(slide, page, ctx);
        break;

      case "full_bleed_visual":
        renderFullBleedVisual(slide, page, ctx);
        break;

      case "four_metric_dashboard":
      case "big_statistic":
        renderBigStatistic(slide, page, ctx);
        break;

      case "comparison_table":
      case "comparison":
        renderComparison(slide, page, ctx);
        break;

      case "horizontal_timeline":
      case "timeline":
        renderTimeline(slide, page, ctx);
        break;

      case "process_flowchart":
      case "process_flow":
        renderProcessFlow(slide, page, ctx);
        break;

      case "diagram":
        renderDiagram(slide, page, ctx);
        break;

      case "data_chart_focus":
      case "chart":
        renderChart(slide, page, ctx);
        break;

      case "table":
        renderTable(slide, page, ctx);
        break;

      case "case_study_card":
        renderTwoColumn(slide, page, ctx);
        break;

      case "quote_editorial":
      case "editorial_asymmetrical":
      case "quote":
        renderQuote(slide, page, ctx);
        break;

      case "detailed_information":
        renderTitleAndContent(slide, page, ctx);
        break;

      case "section_divider":
        renderSectionDivider(slide, page, ctx);
        break;

      case "summary":
        renderSummary(slide, page, ctx);
        break;

      case "closing_slide":
        renderClosingSlide(slide, page, ctx);
        break;

      default:
        // Default to standard Title and Content
        renderTitleAndContent(slide, page, ctx);
        break;
    }
  }

  if (visualDirection) {
    visualDirectionTracer.recordTrace({
      projectId,
      documentId,
      visualDirectionId: visualDirection.id,
      variationSeed: visualDirection.variationSeed,
      styleFamily: visualDirection.styleFamily,
      stage: "PPTX_COMPILATION_COMPLETED",
      generatedAtStage: "pptx-builder",
      consumedBy: "PPTX Compiler",
      metadata: { totalSlides: doc.pages.length },
    });
  }

  return pptx;
}
